name: todo_list_flutter_ebac
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  flutter_slidable: ^3.0.1
  sqflite: ^2.3.0
  path: ^1.8.0
  flutter_native_splash: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#1F1F1F" # Cor de fundo da splash screen
  image: assets/logo.png # Caminho da imagem da splash screen
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
